import glob
import re

print("Starting SEO meta tag normalization...")

def strip_existing_tags(html):
    tags_to_remove = [
        r'<meta\s+property="og:title"[^>]*>',
        r'<meta\s+property="og:description"[^>]*>',
        r'<meta\s+property="og:type"[^>]*>',
        r'<meta\s+property="og:url"[^>]*>',
        r'<meta\s+name="twitter:card"[^>]*>',
        r'<meta\s+name="twitter:title"[^>]*>',
        r'<meta\s+name="twitter:description"[^>]*>',
        r'<meta\s+name="author"[^>]*>'
    ]
    for tag in tags_to_remove:
        html = re.sub(tag, '', html, flags=re.IGNORECASE)
    # also remove empty lines generated by removing tags
    html = re.sub(r'\n\s*\n', '\n', html)
    return html

count = 0
for filepath in glob.glob('**/*.html', recursive=True):
    if '.git' in filepath:
        continue
    
    with open(filepath, 'r', encoding='utf-8') as f:
        html = f.read()
        
    title_match = re.search(r'<title>(.*?)</title>', html, re.IGNORECASE)
    desc_match = re.search(r'<meta\s+name="description"\s+content="([^"]+)"', html, re.IGNORECASE)
    canonical_match = re.search(r'<link\s+rel="canonical"\s+href="([^"]+)"', html, re.IGNORECASE)
    
    title = title_match.group(1) if title_match else "Free Online Image Converter"
    desc = desc_match.group(1) if desc_match else "Free, secure, client-side browser image conversion tool."
    url = canonical_match.group(1) if canonical_match else "https://image-converter-rho-six.vercel.app/"
    
    html = strip_existing_tags(html)
    
    seo_block = f"""
  <!-- Standard SEO / Social Meta Tags -->
  <meta name="author" content="Image Converter" />
  <meta property="og:type" content="website" />
  <meta property="og:url" content="{url}" />
  <meta property="og:title" content="{title}" />
  <meta property="og:description" content="{desc}" />
  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:title" content="{title}" />
  <meta name="twitter:description" content="{desc}" />
"""
    
    # insert right before </head>
    html = html.replace('</head>', seo_block + '</head>')
    
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(html)
        count += 1

print(f"Processed {count} HTML files with standardized SEO meta tags.")
